= Projektantrag

Almina Silnovic | {docdate}


== Digitale Meldestelle für städtische Mängel
=== Beschreibung

In zahlreichen Städten und Gemeinden gibt es eine Lücke zwischen Bürgern und den öffentlichen Verwaltungen bei der effektiven Meldung und Lösung kleiner lokaler Probleme. Die Plattform soll es ihnen ermöglichen, lokale Missstände (z.B. beschädigte Straßen, Vandalismus, Müllablagerungen, defekte Straßenlaternen etc.) schnell und einfach an die zuständigen Behörden zu melden. Bürger können über die Plattform das Problem beschreiben, Fotos hochladen, den Standort angeben und den Bearbeitungsstatus verfolgen. Dadurch wird der Meldeprozess für alle Beteiligten vereinfacht.

=== Projektnutzen

Das Projekt verbessert die Lebensqualität der Stadtbewohner. Durch schnelle Meldungen und direkte Weiterleitungen an die zuständigen Stellen werden Infrastruktur, Sicherheit und Umwelt optimiert, während Bürger aktiv in die Stadtgestaltung eingebunden werden.  Die Plattform trägt dazu bei, dass Missstände nicht länger unentdeckt bleiben und schneller behoben werden, was zu einer sauberen und sicheren Umgebung führt.

=== Konsequenzen bei Nichtdurchführung

Die Lebensqualität und generelle Zufriedenheit der Stadtbewohner ist niedriger, da Probleme wie Vandalismus, schlechte Infrastruktur etc. langsamer behoben werden. Sie haben keine Plattform, worauf sie die Defekte melden und aktiv zu einer Verbesserung beitragen können.

=== Ressourcen

Für die erfolgreiche Umsetzung des Projekts wird ein kleines Entwicklerteam benötigt, bestehend aus 2 bis 4 Softwareentwicklern. Dabei soll einer die Rolle des Projektleiters übernehmen. Der zeitliche Aufwand für die Umsetzung des Projekts umfasst eine Entwicklungsphase von etwa 3 bis 5 Monaten. 